<a href="https://colab.research.google.com/github/Mark-G321/Sudoku-solver/blob/main/Sudoku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
grid= [[5,3,0,0,7,0,0,0,0],
       [6,0,0,1,9,5,0,0,0],
       [0,9,8,0,0,0,0,6,0],
       [8,0,0,0,6,0,0,0,3],
       [4,0,0,8,0,3,0,0,1],
       [7,0,0,0,2,0,0,0,6],
       [0,6,0,0,0,0,2,8,0],
       [0,0,0,4,1,9,0,0,0],
       [0,0,0,0,0,0,0,0,0]]
print(np.matrix(grid))


[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [ ]:
def legal(x,y,n): # checks if number n is a legal input at (x,y)
  global grid
  for i in range(9):
    if grid[x][i]==n:
      return False
    if grid[i][y]==n:
      return False
  x0=(x//3)*3 
  y0=(y//3)*3
  for i in range(3): 
    for j in range(3):
      if grid[x0+i][y0+j]==n: #checks if no same number in square
        return False
  return True
    

In [ ]:
def solution(): #prints a solution to sudoku "grid" if exists
  global grid
  for i in range(9):
    for j in range(9):
      if grid[i][j]==0:
        for num in range(1,10):
          if legal(i,j,num):
            grid[i][j]=num 
            solution() # recursivly solve the sudoku 
            grid[i][j]=0 # returns here if previous assignment of number to i,j resulted in a dead end or if additional solutions are required
        return
  print(np.matrix(grid)) # reaches here if grid is full meaning a solutions was found
  input('Print additional solutions?')
          

In [ ]:
solution()

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
Print additional solutions?
[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 7 6 5]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 5 4 1 9 6 3 7]
 [3 4 7 2 8 6 5 1 9]]
Print additional solutions?
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
Print additional solutions?
